### ISSUE TITLE
won't compile on linux mint 17.3

### ISSUE THREAD

**Issue by TheoremVI** [dlenski/openconnect#41]
# Problem description
dlenski, thanks so much for working on this.

Here is my linux mint box info:  Linux whitenuc 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I performed the following commands, but unfortunately the 'make' failed, as seen below. Might you have any ideas to what i'm doing wrong?

$ sudo apt-get install build-essential autoconf automake libgnutls-dev libproxy-dev libxml2-dev libtool vpnc-scripts
$ git clone https://github.com/dlenski/openconnect.git
$ cd openconnect
$ git checkout globalprotect
$ ./autogen.sh
$ ./configure
$ make

maris@whitenuc ~/neteller/openconnect $ make
make  all-recursive
make[1]: Entering directory `/home/maris/neteller/openconnect'
  CC       libopenconnect_la-gnutls.lo
gnutls.c: In function '_openconnect_gnutls_read':
gnutls.c:201:16: error: 'GNUTLS_E_TIMEDOUT' undeclared (first use in this function)
    if (done == GNUTLS_E_TIMEDOUT) {
                ^
gnutls.c:201:16: note: each undeclared identifier is reported only once for each function it appears in
gnutls.c: At top level:
gnutls.c:2580:15: error: conflicting types for 'gnutls_ext_send_func'
 typedef int (*gnutls_ext_send_func) (gnutls_session_t session,
               ^
In file included from gnutls.c:36:0:
/usr/include/gnutls/gnutls.h:806:17: note: previous declaration of 'gnutls_ext_send_func' was here
   typedef int (*gnutls_ext_send_func) (gnutls_session_t session,
                 ^
make[1]: *** [libopenconnect_la-gnutls.lo] Error 1
make[1]: Leaving directory `/home/maris/neteller/openconnect'
make: *** [all] Error 2
maris@whitenuc 

Thanks again.....

**Comment by TheoremVI** [comment]
Please disregard my above question about failure to compile on mint 17.  I discovered "error while running 'make' on my Linux Mint #33" by sham-hq, and that led me to working compile. I just had to install libgnutls28-dev , completely delete the local git repo, then clone the git repo fresh. After that, everything worked perfectly as you instructed for the build. I have not actually been able to test a connection via GlobalProtect, but will do so after the long weekend.....thanks again dlenski

**Comment by dlenski** [comment]
Yeah, you had an old version of GnuTLS libs installed. You don't need to decline the repo: just `git clean -fx` in the existing one should've do it.

**Comment by TheoremVI** [comment]
thanks you sir.....maris

On 2017-07-02 03:15, Dan Lenski wrote:

> Yeah, you had an old version of GnuTLS libs installed. You don't need to decline the repo: just git clean -fx in the existing one should've do it. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/dlenski/openconnect/issues/41#issuecomment-312475308
[2]
